/**
 * Backlog Management Module
 * Purpose: Workflow summary and backlog report generation
 * Part of: AI Workflow Automation v1.0.0
 */

import fs from 'fs/promises';
import path from 'path';

/**
 * Backlog manager for workflow execution tracking
 */
export class Backlog {
  /**
   * Create backlog manager
   * @param {Object} config - Configuration instance
   */
  constructor(config) {
    this.config = config;
  }

  /**
   * Create workflow summary for a completed run
   * @param {Object} options - Summary options
   * @param {Map} options.workflowStatus - Step statuses
   * @param {Object} options.analysisContext - Analysis context
   * @param {boolean} options.dryRun - Dry run mode
   * @returns {Promise<string>} Path to summary file
   */
  async createWorkflowSummary({ workflowStatus, analysisContext, dryRun = false }) {
    const summaryFile = path.join(this.config.backlogRunDir, 'WORKFLOW_SUMMARY.md');

    if (dryRun) {
      console.log(`[DRY RUN] Would create workflow summary: ${summaryFile}`);
      return summaryFile;
    }

    // Ensure directory exists
    await fs.mkdir(this.config.backlogRunDir, { recursive: true });

    const content = this._generateSummaryContent({
      workflowStatus,
      analysisContext,
    });

    await fs.writeFile(summaryFile, content, 'utf8');
    return summaryFile;
  }

  /**
   * Generate summary content
   * @private
   */
  _generateSummaryContent({ workflowStatus, analysisContext }) {
    const metadata = this.config.getMetadata();
    const executionMode = this.config.getExecutionMode();
    const now = new Date().toLocaleString();

    let content = `# Workflow Execution Summary

**Workflow Run ID:** ${metadata.workflowRunId}
**Execution Date:** ${now}
**Script Version:** ${metadata.scriptVersion}
**Mode:** ${executionMode.auto ? 'Automatic' : 'Interactive'}

---

## Execution Overview

### Steps Completed

`;

    // Add step status for steps 0-14
    for (let i = 0; i < 15; i++) {
      const status = workflowStatus.get(i);
      const statusEmoji = this._getStatusEmoji(status?.status);
      content += `- **Step ${i}:** ${statusEmoji}\n`;
    }

    content += `
### Change Analysis

- **Change Scope:** ${analysisContext.changeScope || 'Not specified'}
- **Commits Ahead:** ${analysisContext.commits || '0'}
- **Modified Files:** ${analysisContext.modified || '0'}

---

## Individual Step Reports

`;

    // Note: Step reports would be listed here when they exist
    content += `*Check the backlog directory for individual step reports.*

---

## How to Use These Reports

1. **Review Individual Steps:** Click on any step report above to see detailed findings
2. **Address Issues:** Work through issues by priority (Critical → High → Medium → Low)
3. **Track Progress:** Mark issues as resolved and update documentation
4. **Archive:** Move resolved workflow runs to \`.ai_workflow/backlog/archive/\` for historical reference

---

**Generated by:** ${metadata.scriptName} v${metadata.scriptVersion}
`;

    return content;
  }

  /**
   * Get emoji for step status
   * @private
   */
  _getStatusEmoji(status) {
    const emojiMap = {
      passed: '✅',
      failed: '❌',
      skipped: '⏭️',
      running: '▶️',
      pending: '⏸️',
    };
    return emojiMap[status] || '⏭️';
  }

  /**
   * Create step report in backlog
   * @param {number} stepNumber - Step number
   * @param {Object} reportData - Report data
   * @returns {Promise<string>} Path to report file
   */
  async createStepReport(stepNumber, reportData) {
    const reportFile = path.join(
      this.config.backlogRunDir,
      `step_${String(stepNumber).padStart(2, '0')}.md`
    );

    await fs.mkdir(this.config.backlogRunDir, { recursive: true });

    const content = `# Step ${stepNumber} Report

**Step:** ${reportData.name || `Step ${stepNumber}`}
**Status:** ${reportData.status || 'Unknown'}
**Timestamp:** ${new Date().toLocaleString()}

---

## Summary

${reportData.summary || 'No summary available'}

## Details

${reportData.details || 'No details available'}

---

*Generated by AI Workflow Automation*
`;

    await fs.writeFile(reportFile, content, 'utf8');
    return reportFile;
  }

  /**
   * List all workflow runs in backlog
   * @returns {Promise<Array>} List of workflow run IDs
   */
  async listWorkflowRuns() {
    try {
      const entries = await fs.readdir(this.config.backlogDir, {
        withFileTypes: true,
      });
      return entries.filter((e) => e.isDirectory()).map((e) => e.name);
    } catch (error) {
      if (error.code === 'ENOENT') {
        return [];
      }
      throw error;
    }
  }
}

export default Backlog;
