/**
 * Backlog Management Module (Pure Functions + Wrapper)
 * @version 2.0.0
 * @description Workflow summary and backlog report generation with referential transparency
 * @module lib/backlog
 * Part of: AI Workflow Automation v1.0.0
 */

import fs from 'fs/promises';
import path from 'path';

/**
 * PURE FUNCTIONS - All referentially transparent
 */

/**
 * Get emoji for step status (PURE)
 * @param {string} status - Step status
 * @returns {string} Emoji representation
 */
export function getStatusEmoji(status) {
  const emojiMap = {
    passed: '✅',
    failed: '❌',
    skipped: '⏭️',
    running: '▶️',
    pending: '⏸️',
  };
  return emojiMap[status] || '⏭️';
}

/**
 * Format execution mode for display (PURE)
 * @param {Object} executionMode - Execution mode settings
 * @returns {string} Formatted mode string
 */
export function formatExecutionMode(executionMode) {
  if (executionMode.auto) return 'Automatic';
  if (executionMode.interactive) return 'Interactive';
  if (executionMode.dryRun) return 'Dry Run';
  return 'Unknown';
}

/**
 * Build step status list markdown (PURE)
 * @param {Map} workflowStatus - Step statuses map
 * @param {number} totalSteps - Total number of steps
 * @returns {string} Markdown list of step statuses
 */
export function buildStepStatusList(workflowStatus, totalSteps = 15) {
  let content = '';
  for (let i = 0; i < totalSteps; i++) {
    const status = workflowStatus.get(i);
    const statusEmoji = getStatusEmoji(status?.status);
    content += `- **Step ${i}:** ${statusEmoji}\n`;
  }
  return content;
}

/**
 * Build change analysis section (PURE)
 * @param {Object} analysisContext - Analysis context
 * @returns {string} Markdown section
 */
export function buildChangeAnalysisSection(analysisContext) {
  return `- **Change Scope:** ${analysisContext.changeScope || 'Not specified'}
- **Commits Ahead:** ${analysisContext.commits || '0'}
- **Modified Files:** ${analysisContext.modified || '0'}`;
}

/**
 * Generate workflow summary content (PURE)
 * @param {Object} options - Summary options
 * @param {Object} options.metadata - Workflow metadata
 * @param {Object} options.executionMode - Execution mode settings
 * @param {Map} options.workflowStatus - Step statuses
 * @param {Object} options.analysisContext - Analysis context
 * @param {string} options.timestamp - Formatted timestamp
 * @returns {string} Markdown content
 */
export function generateSummaryContent({
  metadata,
  executionMode,
  workflowStatus,
  analysisContext,
  timestamp,
}) {
  const modeString = formatExecutionMode(executionMode);
  const stepsList = buildStepStatusList(workflowStatus, metadata.totalSteps);
  const changeAnalysis = buildChangeAnalysisSection(analysisContext);

  return `# Workflow Execution Summary

**Workflow Run ID:** ${metadata.workflowRunId}
**Execution Date:** ${timestamp}
**Script Version:** ${metadata.scriptVersion}
**Mode:** ${modeString}

---

## Execution Overview

### Steps Completed

${stepsList}
### Change Analysis

${changeAnalysis}

---

## Individual Step Reports

*Check the backlog directory for individual step reports.*

---

## How to Use These Reports

1. **Review Individual Steps:** Click on any step report above to see detailed findings
2. **Address Issues:** Work through issues by priority (Critical → High → Medium → Low)
3. **Track Progress:** Mark issues as resolved and update documentation
4. **Archive:** Move resolved workflow runs to \`.ai_workflow/backlog/archive/\` for historical reference

---

**Generated by:** ${metadata.scriptName} v${metadata.scriptVersion}
`;
}

/**
 * Generate step report content (PURE)
 * @param {number} stepNumber - Step number
 * @param {Object} reportData - Report data
 * @param {string} timestamp - Formatted timestamp
 * @returns {string} Markdown content
 */
export function generateStepReportContent(stepNumber, reportData, timestamp) {
  return `# Step ${stepNumber} Report

**Step:** ${reportData.name || `Step ${stepNumber}`}
**Status:** ${reportData.status || 'Unknown'}
**Timestamp:** ${timestamp}

---

## Summary

${reportData.summary || 'No summary available'}

## Details

${reportData.details || 'No details available'}

---

*Generated by AI Workflow Automation*
`;
}

/**
 * IMPURE WRAPPER CLASS - Isolates side effects at boundaries
 */
export class Backlog {
  /**
   * Create backlog manager
   * @param {Object} config - Configuration instance
   */
  constructor(config) {
    this.config = config;
  }

  /**
   * Create workflow summary for a completed run (IMPURE wrapper)
   * @param {Object} options - Summary options
   * @param {Map} options.workflowStatus - Step statuses
   * @param {Object} options.analysisContext - Analysis context
   * @param {boolean} options.dryRun - Dry run mode
   * @returns {Promise<string>} Path to summary file
   */
  async createWorkflowSummary({ workflowStatus, analysisContext, dryRun = false }) {
    const summaryFile = path.join(this.config.backlogRunDir, 'WORKFLOW_SUMMARY.md');

    if (dryRun) {
      console.log(`[DRY RUN] Would create workflow summary: ${summaryFile}`);
      return summaryFile;
    }

    // Ensure directory exists
    await fs.mkdir(this.config.backlogRunDir, { recursive: true });

    // Use pure function for content generation
    const metadata = this.config.getMetadata();
    const executionMode = this.config.getExecutionMode();
    const timestamp = new Date().toLocaleString(); // Inject timestamp here

    const content = generateSummaryContent({
      metadata,
      executionMode,
      workflowStatus,
      analysisContext,
      timestamp,
    });

    await fs.writeFile(summaryFile, content, 'utf8');
    return summaryFile;
  }

  /**
   * Create step report in backlog (IMPURE wrapper)
   * @param {number} stepNumber - Step number
   * @param {Object} reportData - Report data
   * @returns {Promise<string>} Path to report file
   */
  async createStepReport(stepNumber, reportData) {
    const reportFile = path.join(
      this.config.backlogRunDir,
      `step_${String(stepNumber).padStart(2, '0')}.md`
    );

    await fs.mkdir(this.config.backlogRunDir, { recursive: true });

    // Use pure function for content generation
    const timestamp = new Date().toLocaleString(); // Inject timestamp here
    const content = generateStepReportContent(stepNumber, reportData, timestamp);

    await fs.writeFile(reportFile, content, 'utf8');
    return reportFile;
  }

  /**
   * List all workflow runs in backlog (IMPURE - file I/O)
   * @returns {Promise<Array>} List of workflow run IDs
   */
  async listWorkflowRuns() {
    try {
      const entries = await fs.readdir(this.config.backlogDir, {
        withFileTypes: true,
      });
      return entries.filter((e) => e.isDirectory()).map((e) => e.name);
    } catch (error) {
      if (error.code === 'ENOENT') {
        return [];
      }
      throw error;
    }
  }
}

export default Backlog;
