export {
  Step0Analyzer,
  CHANGE_SCOPE,
  FILE_CATEGORY,
  classifyFile,
  classifyFiles,
  determineChangeScope,
  formatAnalysisSummary,
  createBacklogContent,
} from './step_00_analyze.js';
export {
  Step1DocumentationAnalyzer,
  validateDocumentationCounts,
  checkVersionReferences,
  classifyChangedFiles,
  shouldRunAiAnalysis,
} from './step_01_documentation.js';
export {
  Step1_5CopilotInstructionsValidator,
  COPILOT_INSTRUCTIONS_RELATIVE_PATH,
  ensureTrailingNewline,
  extractCopilotInstructionsFindings,
  extractCorrectedCopilotInstructions,
  buildCopilotInstructionsRepoFactsContext,
} from './step_01_5_copilot_instructions.js';
export {
  Step2ConsistencyAnalyzer,
  validateSemver,
  extractVersions,
  checkVersionConsistency,
  extractLinks,
  isFileReference,
  normalizeFilePath,
  validateFileReferences,
  formatConsistencyReport,
  ISSUE_TYPE,
} from './step_02_consistency.js';
export {
  Step3ScriptAnalyzer,
  getScriptPatterns,
  getScriptDirectories,
  extractScriptReferences,
  validateScriptReferences,
  validateShebang,
  isScriptDocumented,
  formatScriptReport,
  SCRIPT_ISSUE_TYPE,
} from './step_03_script_refs.js';
export {
  Step4ConfigAnalyzer,
  CONFIG_PATTERNS,
  SECRET_PATTERNS,
  CONFIG_ISSUE_TYPE,
  isConfigFile,
  getConfigType,
  validateJsonSyntax,
  validateYamlSyntax,
  validateConfigSyntax,
  scanForSecrets,
  checkConfigBestPractices,
  formatConfigReport,
} from './step_04_config_validation.js';
export {
  Step5DirectoryAnalyzer,
  DIR_CATEGORIES,
  CATEGORY_PATTERNS,
  CATEGORY_DIRS,
  ROOT_ALLOWED_FILES,
  EXCLUDED_DIRS,
  shouldStayInRoot,
  categorizeMisplacedDoc,
  getTargetDir,
  shouldIncludeDir,
  extractCriticalDirs,
  getDefaultCriticalDirs,
  isDirectoryDocumented,
  validateDirectoryStructure,
  formatDirectoryReport,
} from './step_05_directory.js';
export {
  Step6TestReviewer,
  TEST_PATTERNS,
  COVERAGE_PATHS,
  getTestPatterns,
  getCoveragePaths,
  isTestFile,
  categorizeTestFiles,
  parseCoveragePercentage,
  getCoverageStatus,
  calculateTestStatistics,
  formatTestReport,
} from './step_06_test_review.js';
export {
  Step7TestGenerator,
  SOURCE_PATTERNS,
  TEST_FILE_PATTERNS,
  EXCLUDE_FILES,
  EXCLUDE_DIRS,
  getSourcePatterns,
  getTestPatterns as getTestFilePatterns,
  shouldExcludeFile,
  hasCorrespondingTest,
  findUntestedFiles,
  calculateCoverage,
  categorizeUntestedFiles,
  formatTestGenerationReport,
} from './step_07_test_gen.js';
export {
  Step8TestExecutor,
  TEST_COMMANDS,
  COVERAGE_FILES,
  TEST_RESULT_PATTERNS,
  getTestCommand,
  getCoverageFiles,
  hasTestScript,
  extractTestCommand,
  parseJestOutput,
  parsePytestOutput,
  parseTestOutput,
  parseJestCoverage,
  determineTestStatus,
  formatTestReport as formatTestExecutionReport,
} from './step_08_test_exec.js';
export {
  Step9DependencyValidator,
  DEPENDENCY_FILES,
  AUDIT_COMMANDS,
  OUTDATED_COMMANDS,
  SEVERITY,
  getDependencyFiles,
  getAuditCommand,
  getOutdatedCommand,
  supportsDependencyValidation,
  parsePackageJson,
  parseNpmAudit,
  parseNpmOutdated,
  determineSeverity,
  formatDependencyReport,
} from './step_09_dependencies.js';
export {
  Step10CodeQualityAnalyzer,
  LINTER_COMMANDS,
  SOURCE_EXTENSIONS,
  QUALITY_THRESHOLDS,
  getLinterCommand,
  getSourceExtensions,
  isSourceFile,
  extractLinterCommand,
  parseEslintOutput,
  parseFlake8Output,
  parseLinterOutput,
  calculateIssueRate,
  determineQualityRating,
  formatQualityReport,
} from './step_10_code_quality.js';
export {
  Step11ContextAnalyzer,
  IMPACT_THRESHOLDS,
  COMPLETION_THRESHOLDS,
  calculateCompletionRate,
  determineCompletionStatus,
  calculateImpactScore,
  determineImpactLevel,
  aggregateIssues,
  calculateDuration,
  formatDuration as formatContextDuration,
  formatContextReport,
} from './step_11_context.js';
export {
  Step12GitFinalization,
  COMMIT_TYPES,
  CHANGE_CATEGORIES,
  GIT_OPERATIONS,
  parseGitStatus,
  categorizeFiles,
  inferCommitType,
  calculateImpactScore as calculateGitImpactScore,
  generateCommitMessage,
  parseDiffSummary,
  parseCommitCounts,
  formatGitReport,
} from './step_12_git_finalization.js';
export {
  Step13MarkdownLint,
  MARKDOWN_PATTERNS,
  ANTI_PATTERNS,
  LINTER_COMMANDS as MARKDOWN_LINTER_COMMANDS,
  SEVERITY_LEVELS,
  filterMarkdownFiles,
  shouldExcludePath,
  parseMdlOutput,
  groupIssuesByFile,
  groupIssuesByRule,
  calculateLintStats,
  checkMissingSpaceAfterHash,
  checkMalformedBold,
  checkTrailingWhitespace,
  checkMultipleBlankLines,
  detectAntiPatterns,
  formatLintReport,
  determineLintStatus,
} from './step_13_markdown_lint.js';
export {
  Step14PromptEngineer,
  PROJECT_TYPES,
  PROMPT_QUALITY_CRITERIA,
  QUALITY_THRESHOLDS as PROMPT_QUALITY_THRESHOLDS,
  shouldRunPromptAnalysis,
  extractPersonaNames,
  extractPromptContent,
  calculatePromptQuality,
  determineQualityRating as determinePromptQualityRating,
  identifyImprovements,
  calculateAggregateStats,
  formatAnalysisReport,
} from './step_14_prompt_engineer.js';
export {
  Step15UxAnalysis,
  UI_PROJECT_TYPES,
  UI_FILE_PATTERNS,
  UX_CATEGORIES,
  SEVERITY_LEVELS as UX_SEVERITY_LEVELS,
  shouldRunUxAnalysis,
  shouldExcludeFile as shouldExcludeUxFile,
  isUiFile,
  categorizeUiFile,
  filterUiFiles,
  groupUiFilesByType,
  buildUxAnalysisPrompt,
  calculateSeverityScore,
  parseUxAnalysisResult,
  formatUxAnalysisReport,
} from './step_15_ux_analysis.js';
export {
  Step16VersionUpdate,
  SEMVER_PATTERN,
  VERSION_PATTERN_REGEX,
  BUMP_TYPES,
  METADATA_FILES,
  HEURISTIC_THRESHOLDS,
  extractVersion,
  parseVersion as parseSemanticVersion,
  incrementVersion,
  detectVersionPatterns,
  replaceVersion,
  determineHeuristicBumpType,
  parseAiBumpRecommendation,
  buildVersionBumpPrompt,
  calculateUpdateStats,
  formatVersionUpdateReport,
} from './step_16_version_update.js';
export {
  Step0bBootstrapDocs,
  DOC_TYPES,
  DOC_THRESHOLDS,
  SOURCE_EXTENSIONS as DOC_SOURCE_EXTENSIONS,
  shouldBootstrapDocs,
  identifyMissingDocs,
  categorizeMissingDocs,
  filterSourceFiles,
  countFilesByExtension,
  determinePrimaryLanguage,
  buildTechnicalWriterPrompt as buildBootstrapDocPrompt,
  formatGapAnalysisReport,
} from './step_0b_bootstrap_docs.js';
export {
  DocumentationOptimizer,
  DEFAULT_CONFIG as DOC_OPTIMIZE_DEFAULT_CONFIG,
  PHASES as DOC_OPTIMIZE_PHASES,
  mergeConfig as mergeDocOptimizeConfig,
  validateConfig as validateDocOptimizeConfig,
  createInitialState as createDocOptimizeState,
  updateState as updateDocOptimizeState,
  aggregateResults as aggregateDocOptimizeResults,
  calculateExecutionTime as calculateDocOptimizeExecutionTime,
} from './step_02_5_doc_optimize.js';
export {
  HeuristicsAnalyzer,
  SIMILARITY_THRESHOLDS,
  calculateFileHash as calculateDocFileHash,
  findExactDuplicates,
  levenshteinDistance,
  extractDocumentTitle,
  normalizeTitle,
  calculateTitleSimilarity,
  extractSignificantWords,
  calculateJaccardSimilarity,
  calculateContentSimilarity,
  calculateSizeSimilarity,
  calculateCombinedSimilarity,
  findRedundantPairs,
} from './step_02_5_lib/heuristics.js';
export {
  GitAnalyzer,
  GIT_THRESHOLDS,
  parseGitLog as parseGitLogForDocs,
  extractLastModified,
  countRecentCommits,
  calculateAgeMonths,
  isRecentlyModified,
  determineStalenessLevel,
  calculateStalenessScore,
  countFileReferences,
  findReferencingFiles,
} from './step_02_5_lib/git_analysis.js';
export {
  VersionAnalyzer,
  VERSION_THRESHOLDS,
  extractVersionReferences,
  parseVersion as parseDocVersion,
  compareVersions as compareDocVersions,
  calculateVersionGap,
  isVersionOutdated,
  calculateVersionStaleness,
  findOldestVersion,
  findNewestVersion,
} from './step_02_5_lib/version_analysis.js';
export {
  ConsolidationManager,
  ARCHIVE_STRUCTURE,
  selectKeepFile,
  buildConsolidationPlan,
  generateArchivePath,
  generateArchiveDirectories,
  calculateConsolidationStats,
  formatConsolidationAction,
} from './step_02_5_lib/consolidation.js';
export {
  ReportingManager,
  REPORT_SECTIONS,
  DEFAULT_RECOMMENDATIONS as DOC_OPTIMIZE_RECOMMENDATIONS,
  calculateTotalSize as calculateDocTotalSize,
  calculateSizeSavings,
  estimateTokenSavings,
  calculateOptimizationMetrics,
  formatTimestamp as formatDocTimestamp,
  formatFileList,
  formatRedundantPairs,
  formatSummarySection,
  formatActionsSection,
  formatRecommendationsSection,
  formatArchiveSection,
  generateOptimizationReport,
  formatConsoleSummary as formatDocConsoleSummary,
} from './step_02_5_lib/reporting.js';
export {
  AiAnalyzer,
  CONFIDENCE_THRESHOLDS as AI_CONFIDENCE_THRESHOLDS,
  ANALYSIS_RESULT,
  isEdgeCase,
  filterEdgeCases,
  countEdgeCases,
  buildRedundancyPrompt,
  parseAiResponse as parseAiRedundancyResponse,
  calculateConfidenceBoost,
  applyAiAnalysis,
  generateAnalysisSummary as generateAiAnalysisSummary,
} from './step_02_5_lib/ai_analyzer.js';
