/**
 * @fileoverview Step 11.6: AWS Serverless AI Review (v2.0.0)
 * @module steps/step_11_6_aws_serverless_review
 *
 * AI-powered review of `aws_lbs_backend_setup` projects using the
 * `aws_serverless_engineer` persona. Evaluates deployment readiness,
 * IAM hygiene, Lambda packaging, and shell script safety.
 *
 * Slots between step_11_5_aws_lbs_validation and step_13_markdown_lint.
 * Skips automatically for all non-aws_lbs_backend_setup project kinds.
 *
 * Architecture: v2.0.0 Referential Transparency
 * - Pure functions for context building, prompt assembly, and report formatting
 * - Impure wrapper class for AI calls, file I/O, and logging
 *
 * @version 2.0.0
 * @since 2026-02-21
 */

import { STEP_KIND } from './step_contract.js';
import { logger } from '../core/logger.js';
import { Backlog } from '../lib/backlog.js';
import { AiHelper } from '../lib/ai_helpers.js';
import { AiCache } from '../lib/ai_cache.js';
import { buildAwsServerlessPrompt } from '../lib/ai_prompt_builder.js';

// ============================================================================
// CONSTANTS
// ============================================================================

/** Project kind this step targets. */
export const AWS_LBS_PROJECT_KIND = 'aws_lbs_backend_setup';

/** AI persona used for the review. */
export const PERSONA_ID = 'aws_serverless_engineer';

// ============================================================================
// PURE FUNCTIONS
// ============================================================================

/**
 * Determine whether this step should run for the given project kind.
 * @pure
 * @param {string} projectKind - Project kind identifier
 * @returns {boolean} True if the step should run
 * @example
 * shouldRunAwsServerlessReview('aws_lbs_backend_setup'); // true
 * shouldRunAwsServerlessReview('nodejs_api');            // false
 */
export function shouldRunAwsServerlessReview(projectKind) {
  return typeof projectKind === 'string' && projectKind.trim() === AWS_LBS_PROJECT_KIND;
}

/**
 * Build a review context object from step_11_5 output and execution context.
 * Falls back to empty arrays when step_11_5 was skipped or unavailable.
 *
 * @pure
 * @param {Object} [step11_5Result={}] - Result object from step_11_5
 * @param {string} [projectRoot=''] - Project root path
 * @returns {Object} Normalised review context
 */
export function buildReviewContext(step11_5Result = {}, projectRoot = '') {
  const shellScripts = Array.isArray(step11_5Result.shellScripts)
    ? step11_5Result.shellScripts
    : [];
  const lambdaFunctions = Array.isArray(step11_5Result.lambdaFunctions)
    ? step11_5Result.lambdaFunctions
    : [];
  const awsConfigKeys =
    step11_5Result.awsConfigValid && step11_5Result.awsConfigKeys
      ? step11_5Result.awsConfigKeys
      : [];

  return { shellScripts, lambdaFunctions, awsConfigKeys, projectRoot };
}

/**
 * Format a Markdown wrapper around the raw AI review response.
 *
 * @pure
 * @param {string} aiResponse - Raw text from the AI helper
 * @param {Object} reviewContext - Context passed to the AI (for metadata)
 * @returns {string} Formatted Markdown report
 */
export function formatAiReviewReport(aiResponse, reviewContext = {}) {
  const { shellScripts = [], lambdaFunctions = [], projectRoot = '' } = reviewContext;

  let report = `# AWS Serverless AI Review\n\n`;
  report += `**Persona:** \`${PERSONA_ID}\`\n`;
  if (projectRoot) report += `**Project:** \`${projectRoot}\`\n`;
  report += `**Shell scripts reviewed:** ${shellScripts.length}\n`;
  report += `**Lambda handlers reviewed:** ${lambdaFunctions.length}\n\n`;
  report += `---\n\n`;
  report += aiResponse || '_(No AI response received)_';
  report += '\n\n---\n\n*Generated by AI Workflow Automation*\n';

  return report;
}

// ============================================================================
// IMPURE WRAPPER
// ============================================================================

/**
 * Step 11.6: AWS Serverless AI Reviewer
 *
 * Uses the `aws_serverless_engineer` AI persona to evaluate deployment
 * readiness of `aws_lbs_backend_setup` projects. Skips for all other kinds.
 *
 * @class
 */
export class Step11_6AwsServerlessReviewer {
  static stepKind = STEP_KIND.PROJECT;

  /**
   * @param {Object} [deps={}] - Injected dependencies
   * @param {Object} [deps.backlog] - Backlog instance
   * @param {Object} [deps.aiHelper] - AiHelper instance
   * @param {Object} [deps.aiCache] - AiCache instance
   * @param {Object} [deps.projectKindConfig] - ProjectKindConfigManager instance
   */
  constructor(deps = {}) {
    this.backlog = deps.backlog || new Backlog();
    this.aiHelper = deps.aiHelper || new AiHelper();
    this.aiCache = deps.aiCache || new AiCache();
    this.projectKindConfig = deps.projectKindConfig || null;
  }

  /**
   * Execute Step 11.6: AWS Serverless AI Review.
   *
   * @async
   * @param {string} projectRoot - Absolute path to the project root
   * @param {Object} [options={}] - Execution options
   * @param {string} [options.projectKind] - Override detected project kind
   * @param {Object} [options.step11_5Result] - Output from step_11_5 (shell scripts, lambdas)
   * @returns {Promise<Object>} Step result
   */
  async execute(projectRoot, options = {}) {
    try {
      logger.step('Step 11.6: AWS Serverless AI Review');

      // ── Gate ──────────────────────────────────────────────────────────────
      const projectKind =
        options.projectKind ??
        (this.projectKindConfig ? await this.projectKindConfig.getProjectKind() : null) ??
        '';
      if (!shouldRunAwsServerlessReview(projectKind)) {
        const msg = projectKind
          ? `Step 11.6 skipped — project kind '${projectKind}' is not aws_lbs_backend_setup`
          : `Step 11.6 skipped — no project kind provided`;
        logger.info(msg);
        return { success: true, skipped: true, reason: msg };
      }

      // ── Build review context from step_11_5 output ───────────────────────
      // options.step11_5Result may be set directly (tests / manual calls), or
      // resolved from the accumulated context.results array that the workflow
      // engine threads through all PROJECT step executions.
      const step11_5Result =
        options.step11_5Result ??
        options.results?.find((r) => r.stepId === 'step_11_5')?.output ??
        {};
      const reviewContext = buildReviewContext(step11_5Result, projectRoot);
      logger.info(
        `Reviewing ${reviewContext.shellScripts.length} shell script(s) and ` +
          `${reviewContext.lambdaFunctions.length} Lambda handler(s)`
      );

      // ── AI review ─────────────────────────────────────────────────────────
      const aiAvailable = await this.aiHelper.initialize();
      let aiResponse = null;

      if (aiAvailable) {
        await this.aiCache.init();
        const prompt = buildAwsServerlessPrompt({
          ...reviewContext,
          projectInfo: { projectKind },
        });
        const cacheKey = [
          'step_11_6',
          reviewContext.shellScripts.length,
          reviewContext.lambdaFunctions.length,
          reviewContext.awsConfigKeys.join(','),
        ].join('|');

        aiResponse = await this.aiCache.withCache(prompt, cacheKey, () =>
          this.aiHelper.executeRequest(prompt, { persona: PERSONA_ID })
        );
        logger.success('AI serverless review completed');
      } else {
        logger.warn('AI helper not available — skipping AI serverless review');
      }

      // ── Save report ───────────────────────────────────────────────────────
      const report = formatAiReviewReport(aiResponse?.content ?? '', reviewContext);
      await this.backlog.saveStepSummary('11_6', 'AWS_Serverless_Review', report);

      return {
        success: true,
        skipped: false,
        aiAvailable,
        aiResponse,
        reviewContext,
        report,
      };
    } catch (error) {
      logger.error(`Step 11.6 failed: ${error.message}`);
      return { success: false, error: error.message };
    }
  }

  /**
   * Return step metadata.
   * @returns {Object} Step metadata
   */
  getMetadata() {
    return {
      id: '11_6',
      name: 'AWS Serverless AI Review',
      description:
        'AI-powered deployment readiness review for aws_lbs_backend_setup projects ' +
        'using the aws_serverless_engineer persona',
      category: 'ai_review',
      estimatedDuration: 30,
      canSkip: true,
      dependencies: ['step_11_5'],
    };
  }
}

export default Step11_6AwsServerlessReviewer;
